export type VehicleDetails = {
  id: string
  immatriculation: string
  type: "Camion" | "Voiture" | "Camionnette"
  marque?: string
  chauffeur: string
  statut: "actif" | "inactif" | "maintenance"
  fonction: string
  kilometrage: number
  carburant: number
  temperature: number
  batterie: number
  position: {
    latitude: number
    longitude: number
    adresse: string
  }
  verrouille: boolean
  moteurAllume: boolean
  climatisation: boolean
  vitesse: number
}

// Données des véhicules basées sur l'OCR fourni
export const vehiclesData: Record<string, VehicleDetails> = {
  v1: {
    id: "v1",
    immatriculation: "GH 002 PE",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Jean Dupont",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 40534,
    carburant: 75,
    temperature: 22,
    batterie: 95,
    position: {
      latitude: 48.8566,
      longitude: 2.3522,
      adresse: "Avenue des Champs-Élysées, Paris",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 65,
  },
  v2: {
    id: "v2",
    immatriculation: "GH 011 PX",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Marie Martin",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 45870,
    carburant: 45,
    temperature: 20,
    batterie: 80,
    position: {
      latitude: 45.764,
      longitude: 4.8357,
      adresse: "Rue de la République, Lyon",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 30,
  },
  v3: {
    id: "v3",
    immatriculation: "GH 093 PD",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Pierre Durand",
    statut: "maintenance",
    fonction: "PATROUILLE",
    kilometrage: 50455,
    carburant: 90,
    temperature: 18,
    batterie: 100,
    position: {
      latitude: 43.2965,
      longitude: 5.3698,
      adresse: "Vieux Port, Marseille",
    },
    verrouille: true,
    moteurAllume: false,
    climatisation: false,
    vitesse: 0,
  },
  v4: {
    id: "v4",
    immatriculation: "GH 113 PY",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Sophie Petit",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 57193,
    carburant: 30,
    temperature: 15,
    batterie: 60,
    position: {
      latitude: 47.2184,
      longitude: -1.5536,
      adresse: "Place du Commerce, Nantes",
    },
    verrouille: true,
    moteurAllume: false,
    climatisation: false,
    vitesse: 0,
  },
  v5: {
    id: "v5",
    immatriculation: "GH 163 PC",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Lucas Bernard",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 57751,
    carburant: 60,
    temperature: 24,
    batterie: 85,
    position: {
      latitude: 43.6045,
      longitude: 1.4442,
      adresse: "Place du Capitole, Toulouse",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 45,
  },
  v6: {
    id: "v6",
    immatriculation: "GH 165 PX",
    type: "Camionnette",
    marque: "Renault",
    chauffeur: "Thomas Moreau",
    statut: "actif",
    fonction: "K9",
    kilometrage: 44351,
    carburant: 55,
    temperature: 21,
    batterie: 90,
    position: {
      latitude: 48.1173,
      longitude: -1.6778,
      adresse: "Place de la République, Rennes",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 0,
  },
  v7: {
    id: "v7",
    immatriculation: "GS 182 PR",
    type: "Voiture",
    marque: "Renault",
    chauffeur: "Camille Dubois",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 21354,
    carburant: 80,
    temperature: 23,
    batterie: 95,
    position: {
      latitude: 43.7102,
      longitude: 7.262,
      adresse: "Promenade des Anglais, Nice",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 50,
  },
  v8: {
    id: "v8",
    immatriculation: "GH 224 PW",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Julie Leroy",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 42325,
    carburant: 65,
    temperature: 22,
    batterie: 85,
    position: {
      latitude: 47.4711,
      longitude: -0.5518,
      adresse: "Place du Ralliement, Angers",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 35,
  },
  v9: {
    id: "v9",
    immatriculation: "GH 251 PV",
    type: "Camionnette",
    marque: "Renault",
    chauffeur: "Alexandre Martin",
    statut: "actif",
    fonction: "K9",
    kilometrage: 30019,
    carburant: 70,
    temperature: 20,
    batterie: 90,
    position: {
      latitude: 44.8378,
      longitude: -0.5792,
      adresse: "Place de la Bourse, Bordeaux",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 0,
  },
  v10: {
    id: "v10",
    immatriculation: "GH 311 PD",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Emma Blanc",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 49101,
    carburant: 40,
    temperature: 21,
    batterie: 75,
    position: {
      latitude: 48.5734,
      longitude: 7.7521,
      adresse: "Place Kléber, Strasbourg",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 40,
  },
  v11: {
    id: "v11",
    immatriculation: "GS 325 PR",
    type: "Voiture",
    marque: "Renault",
    chauffeur: "Nicolas Petit",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 23196,
    carburant: 85,
    temperature: 22,
    batterie: 95,
    position: {
      latitude: 45.764,
      longitude: 4.8357,
      adresse: "Place Bellecour, Lyon",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 55,
  },
  v12: {
    id: "v12",
    immatriculation: "GH 351 PV",
    type: "Camionnette",
    marque: "Renault",
    chauffeur: "Sarah Dumont",
    statut: "actif",
    fonction: "K9",
    kilometrage: 63152,
    carburant: 50,
    temperature: 19,
    batterie: 80,
    position: {
      latitude: 43.6045,
      longitude: 1.4442,
      adresse: "Place du Capitole, Toulouse",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 0,
  },
  v13: {
    id: "v13",
    immatriculation: "GH 402 PC",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Antoine Lefevre",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 54475,
    carburant: 35,
    temperature: 21,
    batterie: 70,
    position: {
      latitude: 47.2184,
      longitude: -1.5536,
      adresse: "Place Graslin, Nantes",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 60,
  },
  v14: {
    id: "v14",
    immatriculation: "GH 416 PV",
    type: "Camionnette",
    marque: "Renault",
    chauffeur: "Léa Rousseau",
    statut: "actif",
    fonction: "K9",
    kilometrage: 38865,
    carburant: 60,
    temperature: 20,
    batterie: 85,
    position: {
      latitude: 48.8566,
      longitude: 2.3522,
      adresse: "Place de la Bastille, Paris",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 0,
  },
  v15: {
    id: "v15",
    immatriculation: "GH 417 PW",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Paul Mercier",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 50602,
    carburant: 45,
    temperature: 22,
    batterie: 75,
    position: {
      latitude: 43.2965,
      longitude: 5.3698,
      adresse: "La Canebière, Marseille",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 45,
  },
  v16: {
    id: "v16",
    immatriculation: "GS 454 PR",
    type: "Voiture",
    marque: "Renault",
    chauffeur: "Chloé Fournier",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 20801,
    carburant: 90,
    temperature: 23,
    batterie: 100,
    position: {
      latitude: 48.1173,
      longitude: -1.6778,
      adresse: "Place de la Mairie, Rennes",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 50,
  },
  v17: {
    id: "v17",
    immatriculation: "GH 458 PX",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Hugo Girard",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 21313,
    carburant: 75,
    temperature: 21,
    batterie: 90,
    position: {
      latitude: 47.4711,
      longitude: -0.5518,
      adresse: "Place du Ralliement, Angers",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 40,
  },
  v18: {
    id: "v18",
    immatriculation: "GH 524 PV",
    type: "Camionnette",
    marque: "Renault",
    chauffeur: "Manon Dupuis",
    statut: "actif",
    fonction: "K9",
    kilometrage: 59664,
    carburant: 55,
    temperature: 20,
    batterie: 80,
    position: {
      latitude: 44.8378,
      longitude: -0.5792,
      adresse: "Place de la Victoire, Bordeaux",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 0,
  },
  v19: {
    id: "v19",
    immatriculation: "GS 569 PQ",
    type: "Voiture",
    marque: "Hyundai",
    chauffeur: "Théo Lemoine",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 22825,
    carburant: 80,
    temperature: 22,
    batterie: 95,
    position: {
      latitude: 48.5734,
      longitude: 7.7521,
      adresse: "Place Kléber, Strasbourg",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 55,
  },
  v20: {
    id: "v20",
    immatriculation: "GH 573 PD",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Inès Morel",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 49677,
    carburant: 40,
    temperature: 21,
    batterie: 75,
    position: {
      latitude: 45.764,
      longitude: 4.8357,
      adresse: "Place des Terreaux, Lyon",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 35,
  },
  v21: {
    id: "v21",
    immatriculation: "GH 620 PX",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Nathan Bertrand",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 53056,
    carburant: 60,
    temperature: 22,
    batterie: 85,
    position: {
      latitude: 43.6045,
      longitude: 1.4442,
      adresse: "Place Wilson, Toulouse",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 45,
  },
  v22: {
    id: "v22",
    immatriculation: "GH 637 PW",
    type: "Camionnette",
    marque: "Renault",
    chauffeur: "Zoé Lambert",
    statut: "actif",
    fonction: "K9",
    kilometrage: 49851,
    carburant: 50,
    temperature: 19,
    batterie: 80,
    position: {
      latitude: 47.2184,
      longitude: -1.5536,
      adresse: "Place Royale, Nantes",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 0,
  },
  v23: {
    id: "v23",
    immatriculation: "GH 688 PB",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Lucas Roux",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 53407,
    carburant: 35,
    temperature: 21,
    batterie: 70,
    position: {
      latitude: 48.8566,
      longitude: 2.3522,
      adresse: "Place de la République, Paris",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 40,
  },
  v24: {
    id: "v24",
    immatriculation: "GS 755 PQ",
    type: "Voiture",
    marque: "Renault",
    chauffeur: "Camille Bonnet",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 27345,
    carburant: 85,
    temperature: 23,
    batterie: 95,
    position: {
      latitude: 43.2965,
      longitude: 5.3698,
      adresse: "Cours Julien, Marseille",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 50,
  },
  v25: {
    id: "v25",
    immatriculation: "GH 793 PW",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Léo Marchand",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 40486,
    carburant: 65,
    temperature: 22,
    batterie: 85,
    position: {
      latitude: 48.1173,
      longitude: -1.6778,
      adresse: "Place Sainte-Anne, Rennes",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 45,
  },
  v26: {
    id: "v26",
    immatriculation: "GH 798 PC",
    type: "Camionnette",
    marque: "Renault",
    chauffeur: "Emma Legrand",
    statut: "actif",
    fonction: "K9",
    kilometrage: 35252,
    carburant: 70,
    temperature: 20,
    batterie: 90,
    position: {
      latitude: 47.4711,
      longitude: -0.5518,
      adresse: "Place du Pilori, Angers",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 0,
  },
  v27: {
    id: "v27",
    immatriculation: "GH 866 PV",
    type: "Camionnette",
    marque: "Renault",
    chauffeur: "Thomas Garnier",
    statut: "actif",
    fonction: "K9",
    kilometrage: 40525,
    carburant: 55,
    temperature: 21,
    batterie: 80,
    position: {
      latitude: 44.8378,
      longitude: -0.5792,
      adresse: "Place Pey Berland, Bordeaux",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 0,
  },
  v28: {
    id: "v28",
    immatriculation: "GS 949 PQ",
    type: "Voiture",
    marque: "Renault",
    chauffeur: "Julie Faure",
    statut: "actif",
    fonction: "PATROUILLE",
    kilometrage: 16007,
    carburant: 90,
    temperature: 23,
    batterie: 100,
    position: {
      latitude: 48.5734,
      longitude: 7.7521,
      adresse: "Place Broglie, Strasbourg",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 55,
  },
  v29: {
    id: "v29",
    immatriculation: "GH 992 PV",
    type: "Camionnette",
    marque: "Renault",
    chauffeur: "Nicolas Roussel",
    statut: "actif",
    fonction: "K9",
    kilometrage: 45477,
    carburant: 50,
    temperature: 19,
    batterie: 80,
    position: {
      latitude: 45.764,
      longitude: 4.8357,
      adresse: "Place des Jacobins, Lyon",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 0,
  },
  v30: {
    id: "v30",
    immatriculation: "GG 481 EM",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Sophie Duval",
    statut: "actif",
    fonction: "LIAISON",
    kilometrage: 28759,
    carburant: 75,
    temperature: 22,
    batterie: 90,
    position: {
      latitude: 43.6045,
      longitude: 1.4442,
      adresse: "Place Saint-Georges, Toulouse",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 40,
  },
  v31: {
    id: "v31",
    immatriculation: "GG 570 EM",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Alexandre Leroy",
    statut: "actif",
    fonction: "LIAISON",
    kilometrage: 23607,
    carburant: 80,
    temperature: 21,
    batterie: 95,
    position: {
      latitude: 47.2184,
      longitude: -1.5536,
      adresse: "Place du Commerce, Nantes",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 45,
  },
  v32: {
    id: "v32",
    immatriculation: "GG 950 ES",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Marie Dubois",
    statut: "actif",
    fonction: "ASTREINTE",
    kilometrage: 15000,
    carburant: 85,
    temperature: 22,
    batterie: 100,
    position: {
      latitude: 48.8566,
      longitude: 2.3522,
      adresse: "Place de la Concorde, Paris",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 0,
  },
  v33: {
    id: "v33",
    immatriculation: "GK 479 EP",
    type: "Voiture",
    marque: "Peugeot",
    chauffeur: "Pierre Martin",
    statut: "actif",
    fonction: "DG",
    kilometrage: 38296,
    carburant: 90,
    temperature: 23,
    batterie: 95,
    position: {
      latitude: 48.8566,
      longitude: 2.3522,
      adresse: "Avenue Montaigne, Paris",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: true,
    vitesse: 0,
  },
  v34: {
    id: "v34",
    immatriculation: "GK 845 LA",
    type: "Camionnette",
    marque: "Renault",
    chauffeur: "Jean Dupont",
    statut: "actif",
    fonction: "LOG",
    kilometrage: 5326,
    carburant: 70,
    temperature: 20,
    batterie: 90,
    position: {
      latitude: 48.8566,
      longitude: 2.3522,
      adresse: "Rue de Rivoli, Paris",
    },
    verrouille: false,
    moteurAllume: true,
    climatisation: false,
    vitesse: 0,
  },
}

// Fonction pour récupérer tous les véhicules
export function getAllVehicles(): VehicleDetails[] {
  return Object.values(vehiclesData)
}

// Fonction pour récupérer un véhicule par son immatriculation
export function getVehicleByImmatriculation(immatriculation: string): VehicleDetails | undefined {
  return Object.values(vehiclesData).find((vehicle) => vehicle.immatriculation === immatriculation)
}

// Fonction pour récupérer les véhicules par fonction
export function getVehiclesByFunction(fonction: string): VehicleDetails[] {
  return Object.values(vehiclesData).filter((vehicle) => vehicle.fonction === fonction)
}
